remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "default"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
title: Healthcare Data Quality Audit
description: SQL + Power BI audit of a simulated hospital data environment
author:
  name: David Kazakov
